### PR TITLE
QA Click functionalities

### PR DESCRIPTION
**Pull request by h01m3s**

### CODE REVIEW

**Comment by h01m3s** [comment]
[Q&A: Connect Widget with redux store](https://trello.com/c/iKfkppjo/88-qa-connect-widget-with-redux-store)

**Comment by h01m3s** [comment]
[Q&A: Implement click functionalities](https://trello.com/c/a9rXvcnn/85-qa-implement-click-functionalities)

**Comment by dsilberger** [comment]
This doesn't compile for me. I ran npm install after pulling, but still no luck. Is there a branch that I need before this one will work? Error message below.

Failed to compile
./src/components/QA/Answers/AnswerItem.js
Module not found: Can't resolve '../../../redux/actions/reportAnswer' in '/home/dsilberger/hackReactor/zion-greenfield/client/src/components/QA/Answers'

**Comment by dsilberger** [comment]
Compiling and this looks mostly great. A few nits:

Adding a question appears to add an extra dummy question:
image

Not sure if this is lingering debugging stuff or a logic error.

Modal has confusing labels for the email field. The bottom input appears to be for email, but the default light text makes it look like it's a feedback form.
image

Not sure either of these need to be fixed before merging, but if they're easy fixes, it'll make our git flow cleaner if they can be done in this branch.

**Comment by h01m3s** [comment]
* Didn't see any extra dummy question was posted after submit a new question
* Will consider logic for non answered question in the future with styling
* The placeholder is specified in the BRD. Makes nonsense, but it's required.

**Pull request merged**
